# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


GMAIL_USERNAME: genesisb.264@gmail.com
GMAIL_PASSWORD: gene0202
MAILCHIMP_API_KEY: a3e7d1a0089549680d25a4bda88c0aed-us8
MAILCHIMP_LIST_ID: 7660761d6b
DOMAIN_NAME: 
OWNER_EMAIL:   genesisb.264@gmail.com
